// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AntdSelector: typeof import('./src/components/IconSelector/AntdSelector.vue')['default']
    Application: typeof import('./src/components/Application/Application.vue')['default']
    BasicForm: typeof import('./src/components/Form/src/BasicForm.vue')['default']
    BasicModal: typeof import('./src/components/Modal/src/basicModal.vue')['default']
    BasicUpload: typeof import('./src/components/Upload/src/BasicUpload.vue')['default']
    Chooser: typeof import('./src/components/FileChooser/src/Chooser.vue')['default']
    CitySelector: typeof import('./src/components/CitySelector/citySelector.vue')['default']
    ColumnSetting: typeof import('./src/components/Table/src/components/settings/ColumnSetting.vue')['default']
    CountTo: typeof import('./src/components/CountTo/CountTo.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker/datePicker.vue')['default']
    DialogContent: typeof import('./src/components/DialogContent/index.vue')['default']
    EditableCell: typeof import('./src/components/Table/src/components/editable/EditableCell.vue')['default']
    Editor: typeof import('./src/components/Editor/editor.vue')['default']
    FileChooser: typeof import('./src/components/FileChooser/index.vue')['default']
    IconSelector: typeof import('./src/components/IconSelector/index.vue')['default']
    Ionicons5Selector: typeof import('./src/components/IconSelector/Ionicons5Selector.vue')['default']
    LoadingContent: typeof import('./src/components/LoadingContent/index.vue')['default']
    Lockscreen: typeof import('./src/components/Lockscreen/Lockscreen.vue')['default']
    MessageContent: typeof import('./src/components/MessageContent/index.vue')['default']
    Preview: typeof import('./src/components/FileChooser/src/Preview.vue')['default']
    Recharge: typeof import('./src/components/Lockscreen/Recharge.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Table: typeof import('./src/components/Table/src/Table.vue')['default']
    TableAction: typeof import('./src/components/Table/src/components/TableAction.vue')['default']
    Upload: typeof import('./src/components/FileChooser/src/Upload.vue')['default']
    UploadFile: typeof import('./src/components/Upload/uploadFile.vue')['default']
    UploadImage: typeof import('./src/components/Upload/uploadImage.vue')['default']
  }
}

export { }
